-- Ejecutar todo en Supabase: SQL Editor → New query → Run
-- Tablas para el portafolio (lista + detalle + galería)

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cover_image_url text not null,
  caracteristicas_html text,
  descripcion_html text,
  published boolean not null default true,
  orden int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  kind text not null check (kind in ('feature', 'gallery')),
  slot int,
  orden int not null default 0,
  image_url text not null,
  descripcion_html text,
  created_at timestamptz not null default now(),
  constraint project_images_feature_slot check (
    (kind = 'feature' and slot is not null and slot between 1 and 5)
    or (kind = 'gallery' and slot is null)
  )
);

create index if not exists idx_projects_published_orden
  on public.projects (published, orden);

create index if not exists idx_project_images_project_kind
  on public.project_images (project_id, kind);

-- Row Level Security: lectura pública para anon (tu app React)
alter table public.projects enable row level security;
alter table public.project_images enable row level security;

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects"
  on public.projects
  for select
  to anon, authenticated
  using (published = true);

drop policy if exists "Public can read project images" on public.project_images;
create policy "Public can read project images"
  on public.project_images
  for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.projects p
      where p.id = project_images.project_id
        and p.published = true
    )
  );

-- Siguiente paso: ejecutar `admin_rls.sql` (admins, Storage, políticas de escritura).

-- Ejemplo de proyecto (opc borrar después)
-- insert into public.projects (nombre, cover_image_url, caracteristicas_html, descripcion_html, published, orden)
-- values (
--   'Mi primer proyecto',
--   'https://ejemplo.com/portada.jpg',
--   '<div class="container"><p><strong>Ciudad</strong><br/>Santiago</p></div>',
--   '<p>Texto intro del proyecto.</p>',
--   true,
--   0
-- );
